// Demo script to show evening lights security alert formatting
function demoEveningLightsAlert() {
  console.log('🚨 Evening Lights Security Alert Demo\n');

  // Sample data that would be generated by the evening lights monitor
  const sampleLightsData = {
    totalLightsOn: 5,
    lightsByClassroom: {
      'Room 101': [
        {
          deviceName: 'Classroom Controller A1',
          location: 'Front Row',
          lightsOn: ['Main Light', 'Reading Light'],
          count: 2
        }
      ],
      'Room 102': [
        {
          deviceName: 'Classroom Controller B2',
          location: 'Back Row',
          lightsOn: ['Main Light'],
          count: 1
        },
        {
          deviceName: 'Classroom Controller B3',
          location: 'Center Row',
          lightsOn: ['Main Light', 'Projector Light'],
          count: 2
        }
      ],
      'Library': [
        {
          deviceName: 'Library Controller L1',
          location: 'Reading Area',
          lightsOn: ['Ambient Light'],
          count: 1
        }
      ]
    }
  };

  console.log('📊 Sample evening lights check results:');
  console.log(`   Total lights still on: ${sampleLightsData.totalLightsOn}`);
  console.log('   Breakdown by classroom:');

  Object.keys(sampleLightsData.lightsByClassroom).forEach(classroom => {
    const devices = sampleLightsData.lightsByClassroom[classroom];
    console.log(`      ${classroom}:`);
    devices.forEach(device => {
      console.log(`        • ${device.deviceName} (${device.location}): ${device.lightsOn.join(', ')}`);
    });
  });
  console.log('');

  // Create the security alert message
  console.log('📢 Generated Security Alert Message:');
  console.log('=' .repeat(50));

  const alertMessage = `🚨 *Evening Lights Alert*

⚠️ ${sampleLightsData.totalLightsOn} light(s) are still ON after 10:00 AM

${Object.keys(sampleLightsData.lightsByClassroom).map(classroom => {
  const devices = sampleLightsData.lightsByClassroom[classroom];
  let classroomText = `*${classroom}:*\n`;
  devices.forEach(device => {
    classroomText += `  • ${device.deviceName}: ${device.lightsOn.join(', ')}\n`;
  });
  return classroomText;
}).join('\n')}*Time:* ${new Date().toLocaleString()}

*Please investigate and turn off unnecessary lights to save energy.*`;

  console.log(alertMessage);
  console.log('=' .repeat(50));
  console.log('');

  // Show alert data structure
  console.log('📋 Alert Data Structure:');
  const alertData = {
    alertname: 'Evening Lights Security Alert',
    summary: `${sampleLightsData.totalLightsOn} lights still on after 10 AM`,
    description: alertMessage,
    severity: 'warning',
    instance: 'evening_lights_monitor',
    value: sampleLightsData.totalLightsOn
  };

  console.log(JSON.stringify(alertData, null, 2));
  console.log('');

  console.log('✅ Demo completed!');
  console.log('\n🎯 Real-world functionality:');
  console.log('   • Automatically runs every day at 10:00 AM');
  console.log('   • Checks all classroom lights across the building');
  console.log('   • Sends detailed alerts to security personnel via Telegram');
  console.log('   • Helps prevent energy waste and security issues');
  console.log('   • Integrates with existing security alert system');
}

// Run the demo
demoEveningLightsAlert();
console.log('\n🎉 Demo script completed');